version: '3.6'
  
services:
  api-gateway:
    build: .
    ports:
      - 8762:8762
    environment:
      - example=my value  
    volumes:
      - javatmp:/tmp
    
volumes:
  # default dir /var/lib/docker/volumes
  javatmp: